steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:0.14.6'
    args: [ 'init']

  - id: 'terraform plan'
    name: 'hashicorp/terraform:0.14.6'
    args: [ 'plan', '-var-file=variables.tfvars', '-var="project=$PROJECT_ID"', '-var="project_number=$PROJECT_NUMBER"' ]

  - id: 'terraform apply'
    name: 'hashicorp/terraform:0.14.6'
    args: [ 'apply','-auto-approve', '-var-file=variables.tfvars', '-var="project=$PROJECT_ID"', '-var="project_number=$PROJECT_NUMBER"']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/twitter_api_token
    env: 'TF_VAR_twitter_api_token'
